[package]
name = "gltf_wasm_parser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
gltf = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
urlencoding = "2.1"
console_error_panic_hook = "0.1"
js-sys = "0.3"
